# Generated by Django 3.1.8 on 2021-07-14 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20210714_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='visibility',
            field=models.BooleanField(default=True),
        ),
    ]
